kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kube-workshop-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard