apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kube-workshop
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: kube-workshop
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20